branch-defaults:
  default:
    environment: null
  master:
    environment: null
global:
  application_name: echowave-backend
  branch: master
  default_ec2_keyname: null
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: echowave-backend
  sc: git
  workspace_type: Application
